apiVersion: v1
kind: ServiceAccount
metadata:
  name: cilium-policy-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cilium-policy-operator
rules:
  - apiGroups: [ "cilium.airplus.com" ]
    resources: [ "predefinedendpointcatalogs", "predefinedendpointcatalogs/status", "predefinedendpointcatalogs/finalizers" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "cilium.airplus.com" ]
    resources: [ "requiredendpointsets", "requiredendpointsets/status", "requiredendpointsets/finalizers" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "networkpolicies" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "cilium.io" ]
    resources: [ "ciliumnetworkpolicies", "ciliumclusterwidenetworkpolicies", "tracingpoliciesnamespaced" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "pods", "nodes", "namespaces", "services", "endpoints" ]
    verbs: [ "get", "list", "watch", "patch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cilium-policy-operator
subjects:
  - kind: ServiceAccount
    name: cilium-policy-operator
    namespace: default
roleRef:
  kind: ClusterRole
  name: cilium-policy-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cilium-policy-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cilium-policy-operator
  template:
    metadata:
      labels:
        app: cilium-policy-operator
    spec:
      serviceAccountName: cilium-policy-operator
      containers:
        - name: app
          image: cilium-policy-operator:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /etc/config
      volumes:
        - name: config
          configMap:
            name: cilium-policy-operator
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-policy-operator
data:
  application.yaml: |
    reconcilers:
      predefined-endpoint-catalog:
        update-interval: 60
      required-endpoint-set:
        update-interval: 60
---
apiVersion: v1
kind: Service
metadata:
  name: cilium-policy-operator
spec:
  selector:
    app: cilium-policy-operator
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP