---
apiVersion: cilium.airplus.com/v1
kind: TargetSystem
metadata:
  name: example-targetsystems
  namespace: default
spec:
  targets:
    - name: google-dns
      address: 8.8.8.8/32
      port: "53"
      protocol: UDP
    - name: my-internal-service
      address: 10.0.0.0/24
      port: "8080"
      protocol: TCP
#    - name: external-website
#      address: 10.20.30.40/26
#      port: "80"
#      protocol: TCP
    - name: internal-website
      address: 10.20.30.40/26
      port: "80"
      protocol: TCP
