---
apiVersion: cilium.airplus.com/v1
kind: RequiredEndpointSet
metadata:
  name: example-res
  namespace: default
spec:
  targetMatchLabels:
    app: nginx
  predefinedEndpoints:
    - aad-api
    - azure-sql
    - another-website
  customEndpoints:
    - name: web-id
      address: 192.168.178.32
      port: "8080"
      protocol: TCP
    - name: tsys
      address: 10.20.30.40/26
      port: "7676"
      protocol: TCP
