spring:
  application:
    name: cilium-policy-operator

operator:
  # The java-operator-sdk-spring-boot-starter will automatically pick up @Component reconcilers.
  # This section can be used for more specific configuration.
  reconcilers:
    targetsystemreconciler:
      name: targetsystemreconciler
